### ISSUE TITLE
knotMultiplicity errors

### ISSUE THREAD

**Issue by rybectom** [pradeep-pyro/tinynurbs#10]
Hi, props to the nice and fast library. I am setting up some testing of the NURBS curves before I sample them to points using tinynurbs and I ran into two issues with the knotMultiplicity function in check.h.
First, "i" should be used at line 263 instead of "index". Now it evaluates the same element in each iteration.
Then, the variable "mult" should be initialized to 1, since the loop finds the number of equalities among the knot values, but the actual number of equal points is "equalities+1".
T

**Comment by pradeep-pyro** [comment]
Closed in #11
