### ISSUE TITLE
How to load the library to my own project? 

### ISSUE THREAD

**Issue by ZJUTongYang** [pradeep-pyro/tinynurbs#19]
Hello Pardeep, 

I think the code is very good and is what I need. Thanks for the effort. However, after compiling the project, only "unittests" and "ZERO_CHECK" were compiled (I didn't make any changes and only used CMake-gui to create a VS project). In particularly, I cannot find an .lib file to be added to my own project. Could you tell me how to generate the .lib file? 

Regards, 
Tong

**Comment by pradeep-pyro** [comment]
Hi @ZJUTongYang, tinynurbs is header only, so no lib file is generated. You can add it as a dependency through CMake and include the required header files. The parts of the code that you use will get compiled together with your project. Let me know if you have further questions.
