### ISSUE TITLE
Use tinynurbs in IFC.JS

### ISSUE THREAD

**Issue by QuimMoya** [pradeep-pyro/tinynurbs#20]
Hi,

Thanks a lot for this fantastic library! We are the devs of [IFC.js](https://ifcjs.github.io/info/), an open source project to allow anyone to create BIM software. We would like to know if it would be possible for us to use this library, as the license for IFC.js is MIT.

Thanks a lot in advance.

Cheers!

**Comment by pradeep-pyro** [comment]
Hi @QuimMoya, IFC.js looks like a very interesting effort. Please feel free to use the library. If you need to make any changes/fixes here please open a PR. I don't have much time to maintain tinynurbs these days though (hopefully that will change in the future), so I can't provide much support.

**Comment by QuimMoya** [comment]
I developed an inverse projection method for bspline surfaces, if you find it interesting just tell me.
