### ISSUE TITLE
glm dependency

### ISSUE THREAD

**Issue by Karbache** [pradeep-pyro/tinynurbs#6]
Dear pradeep,

I tried to build tinynurbs using cmake, but after building it, tinynurbs doesn't include the glm dependency. I tried multiple times, enabling or disabling TINYNURBS_USE_OWN_GLM but to no avail. Why does this happen and how can i resolve this problem.

Kind regards,
Abdelkader

**Comment by pradeep-pyro** [comment]
Hi, could you please confirm if you recursively cloned the repo and can find glm in the tinynurbs/dependencies folder?
