### ISSUE TITLE
How to get the weight and derivatives of a point wrt to a control point?

### ISSUE THREAD

**Issue by Linxu-Fan** [pradeep-pyro/tinynurbs#9]
Hi, thanks for the amazing project!

I have a NURBS surface and N control points. Now I want to evaluate a point P(u, v). I need the weight w and derivative wu, wuu, wv, wuv and wvv wrt to each control point. Does tinynurbs support this feature? Thanks.

**Comment by pradeep-pyro** [comment]
Hi @glovelfan, You can set weights for the surface control points in [this member](https://github.com/pradeep-pyro/tinynurbs/blob/master/include/tinynurbs/core/surface.h#L56).

Then evaluate the points using [this function](https://github.com/pradeep-pyro/tinynurbs/blob/master/include/tinynurbs/core/evaluate.h#L373), and compute derivatives w.r.t. u and v using [this function](https://github.com/pradeep-pyro/tinynurbs/blob/master/include/tinynurbs/core/evaluate.h#L426). Is this what you're looking for?

**Comment by pradeep-pyro** [comment]
Closing, let me know if you have further questions.
